lotto:
  number-generator:
    facade:
      count: 25
      lowerBand: 1
      upperBand: 99
      timer: "0 0 12 * * 6"
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 5000
          readTimeout: 5000

