spring:
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:63792}
  cache:
    type: redis
    redis:
      time-to-live: PT60M
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27018/lotto-web?authSource=admin

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

lotto:
  result-checker:
    #    lotteryRunOccurrence: "0 55 11 * * 6"
    lotteryRunOccurrence: "*/5 * * * * *"
  number-generator:
    #    lotteryRunOccurrence: "0 0 12 * * 6"
    lotteryRunOccurrence: "*/7 * * * * *"
    facade:
      count: 25
      lowerBand: 1
      upperBand: 99
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 5000
          readTimeout: 5000












